[tool.poetry]
name = "chroma-git"
version = "0.1.0"
description = ""
authors = ["Chashin Efim <69835249+NONVME@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
